t5/Biblioteca/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'signup', to: 'usuarios#new', as: 'signup'
  post 'usuarios', to: 'usuarios#create'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :autors
  resources :livros
  resources :generos
end

t5/Biblioteca/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

t5/Biblioteca/app/models/autor.rb
class Autor < ApplicationRecord
    has_many :livro
end

t5/Biblioteca/app/models/genero.rb
class Genero < ApplicationRecord
    has_many :livro
end

t5/Biblioteca/app/models/livro.rb
class Livro < ApplicationRecord
  belongs_to :autor
  belongs_to :genero
end

t5/Biblioteca/app/models/usuario.rb
class Usuario < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

t5/Biblioteca/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= Usuario.find(session[:usuario_id]) if session[:usuario_id]
  end

  def logged_in?
    !!current_user
  end

  def require_login
    unless logged_in?
      flash[:error] = "Você precisa estar logado para acessar essa página."
      redirect_to login_path
    end
  end

  def require_admin
    unless current_user&.admin?
      flash[:error] = "Você não tem permissão para acessar essa página."
      redirect_to root_path
    end
  end
end

t5/Biblioteca/app/controllers/autors_controller.rb
class AutorsController < ApplicationController
    before_action :require_login
    before_action :require_admin, except: [:index, :show]
    before_action :set_autor, only: [:show, :edit, :update, :destroy]
  
    def index
      @autors = Autor.all
    end
  
    def show
    end
  
    def new
      @autor = Autor.new
    end
  
    def create
      @autor = Autor.new(autor_params)
      if @autor.save
        redirect_to @autor, notice: 'Autor foi criado com sucesso.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @autor.update(autor_params)
        redirect_to @autor, notice: 'Autor foi atualizado com sucesso.'
      else
        render :edit
      end
    end
  
    def destroy
      @autor.destroy
      redirect_to autors_url, notice: 'Autor foi excluído com sucesso.'
    end
  
    private
  
    def set_autor
      @autor = Autor.find(params[:id])
    end
  
    def autor_params
      params.require(:autor).permit(:nome)
    end
  end
  
  

t5/Biblioteca/app/controllers/generos_controller.rb
class GenerosController < ApplicationController
    before_action :require_login
    before_action :require_admin, except: [:index, :show]
    before_action :set_genero, only: [:show, :edit, :update, :destroy]
  
    def index
      @generos = Genero.all
    end
  
    def show
    end
  
    def new
      @genero = Genero.new
    end
  
    def create
      @genero = Genero.new(genero_params)
      if @genero.save
        redirect_to @genero, notice: 'Gênero foi criado com sucesso.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @genero.update(genero_params)
        redirect_to @genero, notice: 'Gênero foi atualizado com sucesso.'
      else
        render :edit
      end
    end
  
    def destroy
      @genero.destroy
      redirect_to generos_url, notice: 'Gênero foi excluído com sucesso.'
    end
  
    private
  
    def set_genero
      @genero = Genero.find(params[:id])
    end
  
    def genero_params
      params.require(:genero).permit(:nome)
    end
  end
  
  

t5/Biblioteca/app/controllers/home_controller.rb
class HomeController < ApplicationController
   helper_method :current_user, :logged_in?

   def index
    end
  end
  
  def admin?
    !!Usuario.admin
  end

t5/Biblioteca/app/controllers/livros_controller.rb
class LivrosController < ApplicationController
    before_action :require_login
    before_action :require_admin, except: [:index, :show]
    before_action :set_livro, only: [:show, :edit, :update, :destroy]
  
    def index
      @livros = Livro.all
    end
  
    def show
    end
  
    def new
      @livro = Livro.new
    end
  
    def create
      @livro = Livro.new(livro_params)
      if @livro.save
        redirect_to @livro, notice: 'Livro foi criado com sucesso.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @livro.update(livro_params)
        redirect_to @livro, notice: 'Livro foi atualizado com sucesso.'
      else
        render :edit
      end
    end
  
    def destroy
      @livro.destroy
      redirect_to livros_url, notice: 'Livro foi excluído com sucesso.'
    end
  
    private
  
    def set_livro
      @livro = Livro.find(params[:id])
    end
  
    def livro_params
      params.require(:livro).permit(:titulo, :autor_id, :genero_id)
    end
  end
  
  

t5/Biblioteca/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    usuario = Usuario.find_by(username: params[:username])
    if usuario && usuario.authenticate(params[:password])
      session[:usuario_id] = usuario.id
      redirect_to root_path, notice: 'Login realizado com sucesso!'
    else
      flash.now[:alert] = 'Usuário ou senha inválidos'
      render :new
    end
  end

  def destroy
    session[:usuario_id] = nil
    redirect_to root_path, notice: 'Logout realizado com sucesso!'
  end
end

t5/Biblioteca/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :require_login, except: [:new, :create]

  def new
    @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.new(usuario_params)
    if @usuario.save
      session[:usuario_id] = @usuario.id
      redirect_to root_path, notice: 'Usuário criado com sucesso!'
    else
      render :new
    end
  end

  private

  def usuario_params
    params.require(:usuario).permit(:username, :password, :password_confirmation, :admin)
  end
end

t5/Biblioteca/app/helpers/application_helper.rb
module ApplicationHelper
    def admin?
        current_user && current_user.admin?
    end
end

t5/Biblioteca/app/helpers/autors_helper.rb
module AutorsHelper
end

t5/Biblioteca/app/helpers/generos_helper.rb
module GenerosHelper
end

t5/Biblioteca/app/helpers/livros_helper.rb
module LivrosHelper
end

t5/Biblioteca/app/helpers/sessions_helper.rb
module SessionsHelper
end

t5/Biblioteca/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

t5/Biblioteca/app/views/autors/edit.html.erb
<h1><%= action_name.capitalize %> Autor</h1>

<%= form_with model: @autor, local: true do |form| %>
  <% if @autor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@autor.errors.count, "error") %> proibiu esse autor de ser salvo:</h2>
      <ul>
        <% @autor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Voltar', autors_path, class: 'button button-secondary' %>

t5/Biblioteca/app/views/autors/index.html.erb
<h1>Autors</h1>
<%= link_to 'Novo Autor', new_autor_path, class: 'button button-primary' if admin? %>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th class="actions">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @autors.each do |autor| %>
      <tr>
        <td><%= link_to autor.nome, autor %></td>
        <td class="actions">
          <%= link_to 'Editar', edit_autor_path(autor), class: 'button button-secondary' if admin? %>
          <%= link_to 'Excluir', autor, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'button button-primary' if admin? %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

t5/Biblioteca/app/views/autors/new.html.erb
<h1><%= action_name.capitalize %> Autor</h1>

<%= form_with model: @autor, local: true do |form| %>
  <% if @autor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@autor.errors.count, "error") %> proibiu esse autor de ser salvo:</h2>
      <ul>
        <% @autor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Voltar', autors_path, class: 'button button-secondary' %>

t5/Biblioteca/app/views/autors/show.html.erb
<h1><%= @autor.nome %></h1>
<%= link_to 'Editar', edit_autor_path(@autor) if admin? %>
<%= link_to 'Voltar', autors_path, class: 'button button-secondary' %>

t5/Biblioteca/app/views/generos/edit.html.erb
<h1><%= action_name.capitalize %> Gênero</h1>

<%= form_with model: @genero, local: true do |form| %>
  <% if @genero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genero.errors.count, "error") %> proibiu esse gênero de ser salvo:</h2>
      <ul>
        <% @genero.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Voltar', generos_path, class: 'button button-secondary' %>

t5/Biblioteca/app/views/generos/index.html.erb
<h1>Gêneros</h1>
<%= link_to 'Novo Gênero', new_genero_path, class: 'button button-primary' if admin? %>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th class="actions">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @generos.each do |genero| %>
      <tr>
        <td><%= link_to genero.nome, genero %></td>
        <td class="actions">
          <%= link_to 'Editar', edit_genero_path(genero), class: 'button button-secondary' if admin? %>
          <%= link_to 'Excluir', genero, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'button button-primary' if admin? %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

t5/Biblioteca/app/views/generos/new.html.erb
<h1><%= action_name.capitalize %> Gênero</h1>

<%= form_with model: @genero, local: true do |form| %>
  <% if @genero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genero.errors.count, "error") %> proibiu esse gênero de ser salvo:</h2>
      <ul>
        <% @genero.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Voltar', generos_path, class: 'button button-secondary' %>

t5/Biblioteca/app/views/generos/show.html.erb
<h1><%= @genero.nome %></h1>
<%= link_to 'Editar', edit_genero_path(@genero) if admin? %>
<%= link_to 'Voltar', generos_path, class: 'button button-secondary' %>

t5/Biblioteca/app/views/home/index.html.erb
<h1>Bem-vindo à Biblioteca</h1>

<% if logged_in? %>
  <p>Olá, <%= current_user.username %>!</p>
  <p>Explore os <%= link_to 'Autors', autors_path %>, <%= link_to 'Livros', livros_path %> e <%= link_to 'Gêneros', generos_path %>.</p>
<% else %>
  <p>Por favor, efetue o login ou se cadastre em "signup" para iniciar</p>
<% end %>

t5/Biblioteca/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biblioteca</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_importmap_tags %>
  <%= javascript_include_tag 'application', defer: true %>
</head>

<body>
  <nav>
    <% if logged_in? %>
      <%= link_to 'Home', root_path %> |
      <%= link_to 'Logout', logout_path, method: :delete, data: { confirm: 'Tem certeza que deseja sair?' } %> 
    <% else %>
      <%= link_to 'Login', login_path %> |
      <%= link_to 'Signup', signup_path %>
    <% end %>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
</body>
</html>

t5/Biblioteca/app/views/livros/edit.html.erb
<h1><%= action_name.capitalize %> Livro</h1>

<%= form_with model: @livro, local: true do |form| %>
  <% if @livro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@livro.errors.count, "error") %> proibiu esse livro de ser salvo:</h2>
      <ul>
        <% @livro.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :autor_id %>
    <%= form.collection_select :autor_id, Autor.all, :id, :nome %>
  </div>

  <div class="field">
    <%= form.label :genero_id %>
    <%= form.collection_select :genero_id, Genero.all, :id, :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Voltar', livros_path, class: 'button button-secondary'  %>

t5/Biblioteca/app/views/livros/index.html.erb
<h1>Livros</h1>
<%= link_to 'Novo Livro', new_livro_path, class: 'button button-primary' if admin? %>

<table>
  <thead>
    <tr>
      <th>Título</th>
      <th>Autor</th>
      <th>Gênero</th>
      <th class="actions">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @livros.each do |livro| %>
      <tr>
        <td><%= link_to livro.titulo, livro %></td>
        <td><%= livro.autor.nome %></td>
        <td><%= livro.genero.nome %></td>
        <td class="actions">
          <%= link_to 'Editar', edit_livro_path(livro), class: 'button button-secondary' if admin? %>
          <%= link_to 'Excluir', livro, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'button button-primary' if admin? %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

t5/Biblioteca/app/views/livros/new.html.erb
<h1><%= action_name.capitalize %> Livro</h1>

<%= form_with model: @livro, local: true do |form| %>
  <% if @livro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@livro.errors.count, "error") %> proibiu esse livro de ser salvo:</h2>
      <ul>
        <% @livro.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :autor_id %>
    <%= form.collection_select :autor_id, Autor.all, :id, :nome %>
  </div>

  <div class="field">
    <%= form.label :genero_id %>
    <%= form.collection_select :genero_id, Genero.all, :id, :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Voltar', livros_path, class: 'button button-secondary' %>

t5/Biblioteca/app/views/livros/show.html.erb
<h1><%= @livro.titulo %></h1>
<p>Autor: <%= @livro.autor.nome %></p>
<p>Gênero: <%= @livro.genero.nome %></p>
<%= link_to 'Editar', edit_livro_path(@livro) if admin? %>
<%= link_to 'Voltar', livros_path, class: 'button button-secondary' %>

t5/Biblioteca/app/views/usuarios/new.html.erb
<h1>Cadastro de Usuário</h1>

<%= form_with model: @usuario, local: true do |form| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "erro") %> impediram esse usuário de ser salvo:</h2>
      <ul>
        <% @usuario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div>

  <div class="actions">
    <%= form.submit 'Cadastrar' %>
  </div>
<% end %>

<%= link_to 'Voltar', root_path %>